### ISSUE TITLE
能分享下训练的模型吗，我使用您的代码训练效果不好

### ISSUE THREAD

**Issue by lin1490188** [l294265421/multi-turn-alpaca#1]

**Comment by lin1490188** [comment]
![image](https://user-images.githubusercontent.com/30828399/232269767-401151bf-1017-447e-84e3-a5e61de4d959.png)
我的输出是这样的

**Comment by l294265421** [comment]
> ![image](https://user-images.githubusercontent.com/30828399/232269767-401151bf-1017-447e-84e3-a5e61de4d959.png) 我的输出是这样的

可以哈，今晚吧，我把训练的模型放到百度网盘分享出来

**Comment by l294265421** [comment]
> ![image](https://user-images.githubusercontent.com/30828399/232269767-401151bf-1017-447e-84e3-a5e61de4d959.png) 我的输出是这样的
在训练的模型里试了一下你这个问题，答案还可以啊，你用我最新的推断代码试试：https://github.com/l294265421/multi-turn-alpaca/blob/main/multi_turn_alpaca/training_model/alpaca_chatbot.py，看你的答案，有点儿像没有微调的llama
![图片](https://user-images.githubusercontent.com/9948265/232372601-8015f30f-44fd-433b-b1b8-d729697dbc62.png)

**Comment by l294265421** [comment]
> ![image](https://user-images.githubusercontent.com/30828399/232269767-401151bf-1017-447e-84e3-a5e61de4d959.png) 我的输出是这样的
你用我最新的推断代码试试，看你的答案，有点儿像没有微调的llama。在训练的模型里试了一下你这个问题，答案还可以，训练代码和数据跟GitHub库里完全一样
![图片](https://user-images.githubusercontent.com/9948265/232373203-c6bdc047-c4ee-413d-acc1-3f6d27817328.png)

**Comment by lin1490188** [comment]
> > ![image](https://user-images.githubusercontent.com/30828399/232269767-401151bf-1017-447e-84e3-a5e61de4d959.png) 我的输出是这样的
> > 你用我最新的推断代码试试，看你的答案，有点儿像没有微调的llama。在训练的模型里试了一下你这个问题，答案还可以，训练代码和数据跟GitHub库里完全一样
> > ![图片](https://user-images.githubusercontent.com/9948265/232373203-c6bdc047-c4ee-413d-acc1-3f6d27817328.png)

你分享的那个gradio，试了多轮效果非常好，我训练完就很差，不知道什么原因

**Comment by lin1490188** [comment]
> > ![image](https://user-images.githubusercontent.com/30828399/232269767-401151bf-1017-447e-84e3-a5e61de4d959.png) 我的输出是这样的
> 
> 可以哈，今晚吧，我把训练的模型放到百度网盘分享出来

感谢🙏

**Comment by l294265421** [comment]
> > > ![image](https://user-images.githubusercontent.com/30828399/232269767-401151bf-1017-447e-84e3-a5e61de4d959.png) 我的输出是这样的
> > 
> > 
> > 可以哈，今晚吧，我把训练的模型放到百度网盘分享出来
> 
> 感谢🙏
lora权重：
https://pan.baidu.com/s/1JmUI3Dz_YBFypnAvwWGavw?pwd=vr46
